name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 90
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # -------------------------------
      # âœ… Run All Playwright Test Suites
      # -------------------------------

      - name: Run API tests
        run: npm run test:api

      - name: Run E2E NopCommerce tests
        run: npm run test:e2e

      - name: Run Make Appointment tests (test config)
        run: npm run test:make-apt

      - name: Run Make Appointment tests (dev config)
        run: npm run dev:make-apt

      - name: Run Demo test (headed)
        run: npm run demo

      - name: Run Demo test (global)
        run: npm run demo:global

      - name: Run Demo params test
        run: npm run demo:params

      - name: Run Functional Make Appointment test (headed)
        run: npm run make-apt

      - name: Run Login test
        run: npm run login

      - name: Run Multi-Window test
        run: npm run multi-window

      - name: Run Advanced Capabilities test
        run: npm run pw-adv-cap

      - name: Run Tagged Demo test (@smoke)
        run: npm run demo:tag

      - name: Run Demo Hooks test
        run: npm run demo:hooks

      # -------------------------------
      # ðŸ“¦ Upload Playwright HTML Report
      # -------------------------------
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
