name: Playwright Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    timeout-minutes: 90
    runs-on: ubuntu-latest

    # -------------------------------
    # ðŸ§© Environment Variables (from GitHub Secrets)
    # -------------------------------
    env:
      # Runner
      RUNNER: ${{ secrets.RUNNER }}

      # Test CURA Web App
      TEST_USER_NAME: ${{ secrets.TEST_USER_NAME }}
      TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}

      # NopCommerce Web App
      NOP_COMMERCE_USER_NAME: ${{ secrets.NOP_COMMERCE_USER_NAME }}
      NOP_COMMERCE_PASSWORD: ${{ secrets.NOP_COMMERCE_PASSWORD }}

      # API
      RES_API_KEY_VALUE: ${{ secrets.RES_API_KEY_VALUE }}

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # -------------------------------
      # âœ… Run All Playwright Test Suites
      # -------------------------------

      - name: Run API tests
        run: npm run test:api
        continue-on-error: true

      - name: Run E2E NopCommerce tests
        run: npm run test:e2e
        continue-on-error: true

      - name: Run Make Appointment tests (test config)
        run: npm run test:make-apt
        continue-on-error: true

      - name: Run Make Appointment tests (dev config)
        run: npm run dev:make-apt
        continue-on-error: true

      - name: Run Demo test (headed)
        run: npm run demo
        continue-on-error: true

      - name: Run Demo test (global)
        run: npm run demo:global
        continue-on-error: true

      - name: Run Demo params test
        run: npm run demo:params
        continue-on-error: true

      - name: Run Functional Make Appointment test (headed)
        run: npm run make-apt
        continue-on-error: true

      - name: Run Login test
        run: npm run login
        continue-on-error: true

      - name: Run Multi-Window test
        run: npm run multi-window
        continue-on-error: true

      - name: Run Advanced Capabilities test
        run: npm run pw-adv-cap
        continue-on-error: true

      - name: Run Tagged Demo test (@smoke)
        run: npm run demo:tag
        continue-on-error: true

      - name: Run Demo Hooks test
        run: npm run demo:hooks
        continue-on-error: true

      # -------------------------------
      # ðŸ“¦ Upload Playwright HTML Report
      # -------------------------------
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
